name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install sharness
        run: git clone --depth 1 https://github.com/felipec/sharness.git t/sharness
      - run: SHARNESS_TEST_SRCDIR=t/sharness t/main.t
